/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import CSDL.tbLopHoc;
import CSDL.tbSinhVien;
import JPanel.jPQuanLy;
import Models.clsLopHoc;
import java.awt.Image;
import java.io.File;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmThemMoiSV extends javax.swing.JFrame {
    public frmQuanLy fql;
    public jPQuanLy jPQL;
    String masv;
    String ten;
    String ngaysinh;
    Float diem;
    String diachi;
    int malophoc;
    int gioitinh;
    String anh;
    
    /**
     * Creates new form frmThemMoiSV
     */
    public frmThemMoiSV() {
        fql = new frmQuanLy();
        setUndecorated(rootPaneCheckingEnabled);
        initComponents();
        this.setLocationRelativeTo(fql);
        loadClass();
    }
    public void loadClass() {
        tbLopHoc bangLopHoc = new tbLopHoc();
        Vector<clsLopHoc> lopHoc = bangLopHoc.bangLopHoc();
        DefaultComboBoxModel dcb = new DefaultComboBoxModel(lopHoc);
        cbLopHoc.setModel(dcb);
        cbLopHoc.setSelectedIndex(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPExit = new javax.swing.JPanel();
        lblDongUngDung = new javax.swing.JLabel();
        lblAnUngDung = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbThemAnh = new javax.swing.JLabel();
        lbAnhDaiDien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbMaSinhVien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        txtHoVaTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        cbLopHoc = new javax.swing.JComboBox();
        btnThemMoi = new javax.swing.JButton();
        lbLoiMaSinhVien = new javax.swing.JLabel();
        lbLoiHoVaTen = new javax.swing.JLabel();
        lbLoiNgaySinh = new javax.swing.JLabel();
        lbLoiDiaChi = new javax.swing.JLabel();
        lbLoiDiem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        btnThemLop = new javax.swing.JButton();
        lbLoiTenLop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(664, 450));
        getContentPane().setLayout(null);

        jPExit.setBackground(new java.awt.Color(242, 120, 35));
        jPExit.setForeground(new java.awt.Color(242, 120, 35));

        lblDongUngDung.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDongUngDung.setForeground(new java.awt.Color(255, 255, 255));
        lblDongUngDung.setText("X");
        lblDongUngDung.setPreferredSize(new java.awt.Dimension(20, 20));
        lblDongUngDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDongUngDungMouseClicked(evt);
            }
        });

        lblAnUngDung.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblAnUngDung.setForeground(new java.awt.Color(255, 255, 255));
        lblAnUngDung.setText("-");
        lblAnUngDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnUngDungMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPExitLayout = new javax.swing.GroupLayout(jPExit);
        jPExit.setLayout(jPExitLayout);
        jPExitLayout.setHorizontalGroup(
            jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPExitLayout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addComponent(lblAnUngDung)
                .addGap(32, 32, 32)
                .addComponent(lblDongUngDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPExitLayout.setVerticalGroup(
            jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnUngDung, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPExitLayout.createSequentialGroup()
                .addComponent(lblDongUngDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPExit);
        jPExit.setBounds(0, 0, 664, 20);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 120, 35), new java.awt.Color(242, 120, 35)));
        jPanel2.setPreferredSize(new java.awt.Dimension(664, 410));
        jPanel2.setLayout(null);

        lbThemAnh.setBackground(new java.awt.Color(255, 255, 255));
        lbThemAnh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbThemAnh.setForeground(new java.awt.Color(242, 120, 35));
        lbThemAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemAnh.setText("THÊM ẢNH");
        lbThemAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 120, 35), new java.awt.Color(242, 120, 35)));
        lbThemAnh.setOpaque(true);
        lbThemAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThemAnhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbThemAnhMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbThemAnhMousePressed(evt);
            }
        });
        jPanel2.add(lbThemAnh);
        lbThemAnh.setBounds(20, 300, 230, 50);

        lbAnhDaiDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unknown-person .png"))); // NOI18N
        lbAnhDaiDien.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 121, 35), new java.awt.Color(242, 121, 35)));
        jPanel2.add(lbAnhDaiDien);
        lbAnhDaiDien.setBounds(20, 50, 230, 300);

        jLabel1.setBackground(new java.awt.Color(255, 102, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 120, 35));
        jLabel1.setText("THÊM MỚI SINH VIÊN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(263, 13, 212, 33);

        lbMaSinhVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMaSinhVien.setForeground(new java.awt.Color(242, 120, 35));
        lbMaSinhVien.setText("Mã sinh viên:");
        jPanel2.add(lbMaSinhVien);
        lbMaSinhVien.setBounds(263, 57, 79, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 120, 35));
        jLabel3.setText("Họ và tên:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(263, 92, 65, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 120, 35));
        jLabel4.setText("Ngày sinh:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(263, 127, 65, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 120, 35));
        jLabel5.setText("Điểm:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(263, 169, 36, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 120, 35));
        jLabel6.setText("Giới tính:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(263, 213, 53, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 120, 35));
        jLabel7.setText("Địa chỉ:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(263, 253, 45, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 120, 35));
        jLabel8.setText("Lớp học:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(263, 294, 55, 17);
        jPanel2.add(txtMaSinhVien);
        txtMaSinhVien.setBounds(360, 57, 252, 20);
        jPanel2.add(txtHoVaTen);
        txtHoVaTen.setBounds(360, 92, 177, 20);
        jPanel2.add(txtNgaySinh);
        txtNgaySinh.setBounds(360, 127, 116, 20);
        jPanel2.add(txtDiem);
        txtDiem.setBounds(360, 169, 47, 20);
        jPanel2.add(txtDiaChi);
        txtDiaChi.setBounds(360, 253, 252, 20);

        buttonGroup1.add(rbNam);
        rbNam.setSelected(true);
        rbNam.setText("Nam");
        jPanel2.add(rbNam);
        rbNam.setBounds(360, 212, 70, 23);

        buttonGroup1.add(rbNu);
        rbNu.setText("Nữ");
        jPanel2.add(rbNu);
        rbNu.setBounds(470, 210, 70, 23);

        cbLopHoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbLopHoc);
        cbLopHoc.setBounds(360, 294, 110, 20);

        btnThemMoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(242, 120, 35));
        btnThemMoi.setText("THÊM MỚI");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnThemMoi);
        btnThemMoi.setBounds(360, 332, 114, 23);

        lbLoiMaSinhVien.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbLoiMaSinhVien.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbLoiMaSinhVien);
        lbLoiMaSinhVien.setBounds(360, 78, 140, 10);

        lbLoiHoVaTen.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbLoiHoVaTen.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbLoiHoVaTen);
        lbLoiHoVaTen.setBounds(360, 115, 150, 10);

        lbLoiNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbLoiNgaySinh.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbLoiNgaySinh);
        lbLoiNgaySinh.setBounds(360, 152, 116, 10);

        lbLoiDiaChi.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbLoiDiaChi.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbLoiDiaChi);
        lbLoiDiaChi.setBounds(360, 279, 130, 10);

        lbLoiDiem.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbLoiDiem.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbLoiDiem);
        lbLoiDiem.setBounds(360, 195, 120, 10);

        jTabbedPane1.addTab("Thêm mới sinh viên", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 120, 35));
        jLabel2.setText("THÊM MỚI LỚP HỌC");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(221, 38, 184, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 120, 35));
        jLabel9.setText("Tên lớp:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(107, 78, 52, 17);
        jPanel3.add(txtTenLop);
        txtTenLop.setBounds(221, 78, 219, 20);

        btnThemLop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemLop.setForeground(new java.awt.Color(242, 120, 35));
        btnThemLop.setText("THÊM MỚI");
        btnThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemLop);
        btnThemLop.setBounds(220, 120, 140, 23);

        lbLoiTenLop.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbLoiTenLop.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lbLoiTenLop);
        lbLoiTenLop.setBounds(220, 100, 220, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thêm mới lớp học", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 20, 660, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDongUngDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDongUngDungMouseClicked
        // TODO add your handling code here:
        fql.getBtnThemSinhVien().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_lblDongUngDungMouseClicked

    private void lblAnUngDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnUngDungMouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_lblAnUngDungMouseClicked

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        boolean checkResult = txtHoVaTen.getText().equals("") || txtNgaySinh.getText().equals("") || txtDiem.getText().equals("") || txtDiaChi.getText().equals("") || txtMaSinhVien.getText().equals("");
        if (checkResult) {
            if (txtHoVaTen.getText().equals("")) {
                lbLoiHoVaTen.setText("Nhập họ và tên");
            }
            if (txtNgaySinh.getText().equals("")) {
                lbLoiNgaySinh.setText("Nhập ngày sinh");
            }
            if (txtDiem.getText().equals("")) {
                lbLoiDiem.setText("Nhập điểm");
            }
            if (txtDiaChi.getText().equals("")) {
                lbLoiDiaChi.setText("Nhập địa chỉ");
            }
            if(txtMaSinhVien.getText().equals("")) {
                lbLoiMaSinhVien.setText("Nhập địa chỉ");
            }
        }
        else {
            tbSinhVien sv = new tbSinhVien();
            masv = txtMaSinhVien.getText();
            ten = txtHoVaTen.getText();
            ngaysinh = txtNgaySinh.getText();
            diem = Float.parseFloat(txtDiem.getText());
            diachi = txtDiaChi.getText();
            malophoc = cbLopHoc.getSelectedIndex() +1;
            if (rbNam.isSelected()) {
                gioitinh = 1;
            }
            else {
                gioitinh = 2;
            }
            if (anh == null) {
                anh = "";
            }
            boolean result = sv.themMoiSV(masv, ten, ngaysinh, diem, diachi, gioitinh, malophoc, anh);
            if (result) {
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                fql.getBtnThemSinhVien().setEnabled(true);
                jPQL.loadContent("");
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại");
            }
        }
        
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void lbThemAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemAnhMouseClicked
        // TODO add your handling code here:
        JFileChooser openFile = new JFileChooser();
        openFile.showOpenDialog(null);
        File f = openFile.getSelectedFile();
        this.anh = f.getAbsolutePath();
        System.out.println(this.anh);
        ImageIcon icon=null;
        try {
            Image anh_goc = ImageIO.read(f);
            Image anh_sua =anh_goc.getScaledInstance(lbAnhDaiDien.getWidth(), lbAnhDaiDien.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(anh_sua);
        }catch(Exception e){}
        //ImageIcon icon = new ImageIcon(filename);
        lbAnhDaiDien.setIcon(icon);
    }//GEN-LAST:event_lbThemAnhMouseClicked

    private void lbThemAnhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemAnhMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lbThemAnhMouseEntered

    private void lbThemAnhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThemAnhMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_lbThemAnhMousePressed

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        // TODO add your handling code here:
        tbLopHoc lophoc = new tbLopHoc();
        Vector<clsLopHoc> bangLopHoc = lophoc.bangLopHoc();
        
        if (txtTenLop.getText().equals("")) {
            lbLoiTenLop.setText("Nhập tên lớp !");
            return;
        }
        if (!lophoc.timKiem(txtTenLop.getText())) {
            lbLoiTenLop.setText("Tên lớp đã tồn tại");
            return;
        }
        else if (lophoc.themMoiLopHoc(txtTenLop.getText())) {
            JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
            fql.getBtnThemSinhVien().setEnabled(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnThemLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThemMoiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThemMoiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThemMoiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThemMoiSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThemMoiSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbLopHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAnhDaiDien;
    private javax.swing.JLabel lbLoiDiaChi;
    private javax.swing.JLabel lbLoiDiem;
    private javax.swing.JLabel lbLoiHoVaTen;
    private javax.swing.JLabel lbLoiMaSinhVien;
    private javax.swing.JLabel lbLoiNgaySinh;
    private javax.swing.JLabel lbLoiTenLop;
    private javax.swing.JLabel lbMaSinhVien;
    private javax.swing.JLabel lbThemAnh;
    private javax.swing.JLabel lblAnUngDung;
    private javax.swing.JLabel lblDongUngDung;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
